pipeline {
    agent any

    tools {
        maven 'Maven_3_8_7'  // Replace 'Maven_3_8_7' with the name of your Maven installation in Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                // Assuming you've set up a GitHub credential in Jenkins named 'github-credentials'
                //git branch: 'main',
                //        credentialsId: 'github-credentials',
                //        url: 'https://github.com/Mukezz/CIDemoBlog2.git'
                
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'github-credentials', url: 'https://github.com/Mukezz/CIDemoBlog2.git']]])
            }
        }

        stage('Compile') {
            steps {
                script {
                    sh "mvn clean compile"
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh "mvn test"
                }
            }
        }

        stage('Building Jar') {
            steps {
                script {
                    sh 'mvn release:prepare release:perform -Darguments="-Dmaven.deploy.skip=true"'
                }
            }
        }

        stage('Running Dockerfile to create image') {
            steps {
                script {
                    sh "docker built -t devops/mukeshblogpost3 ."
                }
            }
        }
       

        stage('Starting the application docker container') {
            steps {
                script {
                    sh "docker run -p 8080:8080 devops/mukeshblogpost3 -d"
                }
            }
        }              
    }
}
